version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: repsy-postgres
    environment:
      POSTGRES_DB: repsy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    networks:
      - repsy-network

  minio:
    image: minio/minio
    container_name: repsy-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - repsy-network

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repsy_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      STORAGE_TYPE: filesystem
    networks:
      - repsy-network

networks:
  repsy-network:


#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:15
#    container_name: repsy-postgres
#    environment:
#      POSTGRES_DB: repsy_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres123
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#  minio:
#    image: minio/minio
#    container_name: repsy-minio
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin123
#    ports:
#      - "9000:9000"       # Web arayüz
#      - "9001:9001"       # Admin arayüz
#    command: server /data --console-address ":9001"
#    volumes:
#      - minio-data:/data
#
#volumes:
#  postgres-data:
#  minio-data: